// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnkyvhbzthoiykdgkmfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua3l2aGJ6dGhvaXlrZGdrbWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTIzMzksImV4cCI6MjA2NTM2ODMzOX0.WT9tZrXvwro6iV-YqRuEjVpAInOFnKR9Vb4qvjK3nwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);